/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package andrea.tfg.frames;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import static javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER;
import javax.swing.border.Border;

/**
 *
 * @author Andrea
 */
public class AyudaUsoFrame extends javax.swing.JFrame {

    /**
     * Creates new form ayudaUsoFrame
     */
    public AyudaUsoFrame() {
        initComponents();
        
        //Para conseguir que se abra en ventana completa la aplicación.
        //this.setExtendedState(MAXIMIZED_BOTH);
        
        // Instrucciones para que la pantalla de ayuda aparezca en la parte derecha.
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        setSize( 500, (int) pantalla.getHeight() );
        setLocation( (int) pantalla.getWidth() - getWidth(), 0 );
        
        // Esto lo utilizamos para quitar el borde del JTextArea del texto de Ayuda.
        jScrollPane1.setBorder (null);
        
        // Utilizar estas lineas de código para poner el fondo del texto ayuda del mismo color que el del fondo del frame.
        float[] hsbvals = null;
        hsbvals = Color.RGBtoHSB(214 , 217 , 224, hsbvals);
        TextoInfoApp.setBackground(Color.getHSBColor(hsbvals[0], hsbvals[1], hsbvals[2]));
        TituloInfoApp.setBackground(Color.getHSBColor(hsbvals[0], hsbvals[1], hsbvals[2]));
        TextoModoPrede.setBackground(Color.getHSBColor(hsbvals[0], hsbvals[1], hsbvals[2]));
        
        //JScrollPane pane = new JScrollPane (TextoInfoApp, JScrollPane.VERTICAL_SCROLLBAR_NEVER, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        jScrollPane1.setVerticalScrollBarPolicy(VERTICAL_SCROLLBAR_NEVER);
    }
    
    // Método para cambiar el icono de la ventana.
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("andrea/tfg/resources/ayuda.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAyudaUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoInfoApp = new javax.swing.JTextArea();
        TituloInfoApp = new javax.swing.JTextField();
        InfoModoPrede = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextoModoPrede = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        labelAyudaUsuario.setBackground(new java.awt.Color(0, 204, 204));
        labelAyudaUsuario.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        labelAyudaUsuario.setForeground(new java.awt.Color(0, 153, 153));
        labelAyudaUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAyudaUsuario.setText("AYUDA USUARIO");

        jScrollPane1.setHorizontalScrollBar(null);

        TextoInfoApp.setEditable(false);
        TextoInfoApp.setBackground(new java.awt.Color(240, 240, 240));
        TextoInfoApp.setColumns(1);
        TextoInfoApp.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        TextoInfoApp.setLineWrap(true);
        TextoInfoApp.setRows(1);
        TextoInfoApp.setText("Esta aplicación se ha desarrollado para llevar acabo el procedimiento MECDSA (Multiple Ellptic Curves Digital Signature Algorithm), basado eniseño del mismo del paper \"A Secure Multiple Elliptic Curves Digital Signature Algorithm for Blockchain\" de Wei Bi, Xiaoyun Jia y Maolin Zheng. \nEl funcionamineto básico de este sistema es que partiendo de dos curvas elípticas seleccionadas por el usuario y del mensaje que introduce el usuario en la aplicación mediante el algoritmo implementado se obtiene la firma digital del mensaje.\n\n\n");
        TextoInfoApp.setBorder(null);
        TextoInfoApp.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TextoInfoApp.setSelectedTextColor(new java.awt.Color(0, 153, 153));
        TextoInfoApp.setSelectionColor(new java.awt.Color(0, 51, 51));
        jScrollPane1.setViewportView(TextoInfoApp);

        TituloInfoApp.setEditable(false);
        TituloInfoApp.setBackground(new java.awt.Color(240, 240, 240));
        TituloInfoApp.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        TituloInfoApp.setForeground(new java.awt.Color(0, 102, 102));
        TituloInfoApp.setText("Información sobre la aplicación.");
        TituloInfoApp.setBorder(null);
        TituloInfoApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloInfoAppActionPerformed(evt);
            }
        });

        InfoModoPrede.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        InfoModoPrede.setForeground(new java.awt.Color(0, 102, 102));
        InfoModoPrede.setText("Modo predeterminado.");

        jScrollPane2.setBorder(null);

        TextoModoPrede.setEditable(false);
        TextoModoPrede.setColumns(20);
        TextoModoPrede.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        TextoModoPrede.setLineWrap(true);
        TextoModoPrede.setRows(5);
        TextoModoPrede.setText("En este modo el usuario tiene que escoger dos de las curvas proporcionadas, posteriormente tiene que introducir el mensaje que desea firmar y en el cuadro inferior aparecerá el resultado del mensaje firmado. Las curvas a escoger son las que aparecen en las especificaciones.");
        jScrollPane2.setViewportView(TextoModoPrede);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(labelAyudaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1071, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloInfoApp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(InfoModoPrede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAyudaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TituloInfoApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoModoPrede)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TituloInfoAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloInfoAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloInfoAppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AyudaUsoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AyudaUsoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AyudaUsoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AyudaUsoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AyudaUsoFrame().setVisible(true);
            }
        });
        
        JLabel label= new JLabel( "asdf" );
        Border border = BorderFactory.createLineBorder(Color.BLACK);
        label.setBorder(border);
        label.setPreferredSize( new Dimension(150, 100));
    
        label.setText( "Centered" );
        label.setHorizontalAlignment(JLabel.CENTER);
        label.setVerticalAlignment(JLabel.CENTER);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InfoModoPrede;
    private javax.swing.JTextArea TextoInfoApp;
    private javax.swing.JTextArea TextoModoPrede;
    private javax.swing.JTextField TituloInfoApp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAyudaUsuario;
    // End of variables declaration//GEN-END:variables
}
